name: netodesys
channels:
  - conda-forge
  - defaults
dependencies:
  - clangxx_osx-64
  - clang_osx-64
  - python >= 3.6
  - networkx >= 2.0
  - boost
  - sundials <= 4.0.2
  - suitesparse
  - gsl
  - numpy
  - pytest
  - llvm-openmp
  - pip:
      - indexed.py
      - ipdb
      - pyodesys[all]
